apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "cryostat-helm.fullname" . }}-jmx-auth"
type: Opaque
data:
  CRYOSTAT_RJMX_USER: {{ .Values.cryostat.rjmxUser | b64enc | quote }}
  CRYOSTAT_RJMX_PASS: {{ default (randAlphaNum 20) .Values.cryostat.rjmxPassword | b64enc | quote }}
{{- if not .Values.cryostat.minimal }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "cryostat-helm.fullname" . }}-grafana-basic"
type: Opaque
data:
  GF_SECURITY_ADMIN_USER: {{ .Values.cryostat.grafanaUser | b64enc | quote }}
  GF_SECURITY_ADMIN_PASSWORD: {{ default (randAlphaNum 20) .Values.cryostat.grafanaPassword | b64enc | quote }}
{{- end }}