apiVersion: v1
kind: Service
metadata:
  name: {{ include "cryostat-helm.fullname" . }}
  labels:
    component: cryostat
    {{- include "cryostat-helm.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}  
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8181
      targetPort: 8181
      protocol: TCP
      name: export
    - port: 9091
      targetPort: 9091
      protocol: TCP
      name: jfr-jmx
  selector:
    {{- include "cryostat-helm.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ include "cryostat-helm.fullname" . }}-command"
  labels:
    component: command-channel
    {{- include "cryostat-helm.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}  
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 9090
      targetPort: 9090
      protocol: TCP
      name: cmdchan
  selector:
    {{- include "cryostat-helm.selectorLabels" . | nindent 4 }}
{{- if not .Values.cryostat.minimal }}
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ include "cryostat-helm.fullname" . }}-grafana"
  labels:
    component: grafana
    {{- include "cryostat-helm.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}  
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: 3000-tcp
  selector:
    {{- include "cryostat-helm.selectorLabels" . | nindent 4 }}
{{- end }}